### ISSUE TITLE
The downloader doesn't seem to work

### ISSUE THREAD

**Issue by Wanghaiyang1** [vgupta-ai/ISIC-Dataset-Downloader#3]
Hello, thank you for your downloader. May I ask you some questions? 
When I was using the downloader, I could only download 225 of them, not twelve thousand pictures. When I download the 225 pictures, this Downloader is finished, and even when I re download, I still have to download only 225 pictures

**Comment by pingaowang** [comment]
Till now, it works well for me, and has downloaded 10000+ metadata, and still downloading. However I don't start to download pictures, and I found that the number of pictures in the first dataset is 225? Does it mean we need to change the name of dataset in scripts to download different dataset's picture? Let me check it out now.
I'm using Anaconda to control python version, so would you like to create a new Anaconda environment with default configure of python 2.7.
我看你名字是中国人，要是还想用这个下载器的话可以联系我一起学习，我微信 petter1102

**Comment by pingaowang** [comment]
Right now, when the downloader finish the first 225 pictures, it continue download next dataset.
Seems work well.

**Comment by vguptai** [comment]
Things look good. So, closing this issue.
