### ISSUE TITLE
Usage of the pkl file

### ISSUE THREAD

**Issue by Bilguunkhan** [vgupta-ai/ISIC-Dataset-Downloader#4]
Hi, since you have mapped the metadata to the images, which results in "imageIdClassMap.pkl" file, did you use only this file in your ConvNet project (https://github.com/vgupta-ai/Melanoma-Cancer-Detection-V1/tree/version1) ?

**Comment by vguptai** [comment]
You have to download the images also after generating the "imageIdClassMap.pkl" file. This file is just a map.
